import React, { Component } from 'react';
import { hot } from 'react-hot-loader';

import RVGTable from '../src/index';
import { autoGenerateData } from './util';

import './style.css';

class App extends Component {
    componentDidMount() {
        this.table = new RVGTable(this.refs.table, {
            columnWidth: 100,
            rowHeight: 30,
        });
        this.table.mount();

        autoGenerateData((data) => {
            this.table.updateData(data);
        });

        window.table = this.table;
    }

    render() {
        return (
            <div className="App">
                <h1> DEMO for rvgtable </h1>

                <div ref="table" className="table"></div>
            </div>
        );
    }
}

export default hot(module)(App);
