import { generateColumns, autoGenerateData } from './util';
import './style.css';

const RVGTable = window.RVGTable.default;

window.onload = function () {
    let table = new RVGTable(document.querySelector('#table'), {
        columns: generateColumns(),
        columnWidth: 100,
        rowHeight: 30,
    });
    table.mount();

    autoGenerateData((data) => {
        table.updateData([]);
    });
};
