import { generateColumns, autoGenerateData } from './util';
import './style.css';

const RVGTable = window.RVGTable.default;

const COLUMNS = 100;

window.onload = function () {
    const columnWidths = new Array(COLUMNS).fill(0).map(() => 100);

    let table = new RVGTable(document.querySelector('#table'), {
        columns: generateColumns(COLUMNS),
        columnWidth: function ({ index }) {
            return columnWidths[index];
        },
        rowHeight: 30,
        onColumnResize: (columnIndex, delta) => {
            columnWidths[columnIndex] = columnWidths[columnIndex] + delta;

            table.recomputeGridSize(columnIndex);
        },
    });
    table.mount();

    autoGenerateData((data) => {
        table.updateData(data);
    });
};
