const INTERVAL = 100; // 10ms
const COLUMNS = 300;
const ROWS = 300;

let count = 0;
function generateData() {
    const ret = [
        new Array(COLUMNS).fill(0).map((v, i) => `column-${i}`)
    ];

    for (let i = 0; i < ROWS; i++) {
        const item = [];

        for (let j = 0; j < COLUMNS; j++) {
            item.push(`r:${i} c:${j} v:${count}`);
        }

        ret.push(item);
    }

    count++;
    return ret;
}

let timeout = 0;
export function autoGenerateData(cb) {
    if (timeout) {
        clearTimeout(timeout);
    }

    timeout = setTimeout(() => {
        cb(generateData());

        autoGenerateData(cb);
    }, INTERVAL);
}
